version: '3'
services:
  nginx:
    build: ./docker/nginx
    volumes:
      - ./:/var/www/realworld/
    ports:
      - ${NGINX_HOST_PORT:-80}:80
    restart: always
    depends_on:
      - php-fpm
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./:/var/www/realworld/
    links:
      - mysql:realworld.dev
  mysql:
    image: mysql:5.7
    ports:
      - ${DB_HOST_PORT:-3306}:3306
    environment:
      - MYSQL_DATABASE=realworld
      - MYSQL_USER=realworld
      - MYSQL_PASSWORD=realworld
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
